# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mpc_service_pb2 as mpc__service__pb2


class MPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/mpc.MPCService/SendMessage',
                request_serializer=mpc__service__pb2.MessageRequest.SerializeToString,
                response_deserializer=mpc__service__pb2.MessageResponse.FromString,
                )
        self.StreamMessages = channel.unary_stream(
                '/mpc.MPCService/StreamMessages',
                request_serializer=mpc__service__pb2.StreamRequest.SerializeToString,
                response_deserializer=mpc__service__pb2.MessageEvent.FromString,
                )
        self.BidirectionalStream = channel.stream_stream(
                '/mpc.MPCService/BidirectionalStream',
                request_serializer=mpc__service__pb2.MessageRequest.SerializeToString,
                response_deserializer=mpc__service__pb2.MessageEvent.FromString,
                )
        self.GetStats = channel.unary_unary(
                '/mpc.MPCService/GetStats',
                request_serializer=mpc__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=mpc__service__pb2.StatsResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/mpc.MPCService/HealthCheck',
                request_serializer=mpc__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=mpc__service__pb2.HealthResponse.FromString,
                )


class MPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Envío unidireccional de mensaje
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Streaming de mensajes del servidor al cliente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStream(self, request_iterator, context):
        """Streaming bidireccional
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Obtener estadísticas del servidor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=mpc__service__pb2.MessageRequest.FromString,
                    response_serializer=mpc__service__pb2.MessageResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=mpc__service__pb2.StreamRequest.FromString,
                    response_serializer=mpc__service__pb2.MessageEvent.SerializeToString,
            ),
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=mpc__service__pb2.MessageRequest.FromString,
                    response_serializer=mpc__service__pb2.MessageEvent.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=mpc__service__pb2.StatsRequest.FromString,
                    response_serializer=mpc__service__pb2.StatsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mpc__service__pb2.HealthRequest.FromString,
                    response_serializer=mpc__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpc.MPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCService/SendMessage',
            mpc__service__pb2.MessageRequest.SerializeToString,
            mpc__service__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mpc.MPCService/StreamMessages',
            mpc__service__pb2.StreamRequest.SerializeToString,
            mpc__service__pb2.MessageEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mpc.MPCService/BidirectionalStream',
            mpc__service__pb2.MessageRequest.SerializeToString,
            mpc__service__pb2.MessageEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCService/GetStats',
            mpc__service__pb2.StatsRequest.SerializeToString,
            mpc__service__pb2.StatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mpc.MPCService/HealthCheck',
            mpc__service__pb2.HealthRequest.SerializeToString,
            mpc__service__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)